### ISSUE TITLE
matplotlib tries to use X

### ISSUE THREAD

**Issue by 23jodys** [23jodys/fealden#11]
## ERROR: weboutput_tests.solution_output_test_generator(ATTATTAAT, [], [])

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/nose/case.py", line 183, in runTest
    self.test(_self.arg)
  File "/media/cargo/fealden/test/weboutput_tests.py", line 18, in _solution_output_tester
    weboutput.solution_output(sensor, [],[], temp_dir)
  File "/media/cargo/fealden/fealden/weboutput.py", line 121, in solution_output
    plot_gain(Ks, sensor, output_dir)
  File "/media/cargo/fealden/fealden/weboutput.py", line 140, in plot_gain
    fig = plt.figure()
  File "/usr/lib/pymodules/python2.6/matplotlib/pyplot.py", line 254, in figure
    *_kwargs)
  File "/usr/lib/pymodules/python2.6/matplotlib/backends/backend_tkagg.py", line 90, in new_figure_manager
    window = Tk.Tk()
  File "/usr/lib/python2.6/lib-tk/Tkinter.py", line 1646, in **init**
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
TclError: no display name and no $DISPLAY environment variable

**Comment by 23jodys** [comment]
I'd like to see if this issue is resolved now, can you reproduce the error?

**Comment by Paradoxdruid** [comment]
I believe this issue is corrected; the latest errors (in Issue #17 ) happen after this error would have occurred when plot_gain is called.  However, until #17 is fixed I can't be sure.

**Comment by 23jodys** [comment]
I'm going to close this issue, I believe that since the error checking in this portion of the code is not very good, we are likely seeing two seperate errors. If you aren't getting this specific error from Tk, then I think we are good.
