### ISSUE TITLE
Error checking for weboutput should be more robust and log something.

### ISSUE THREAD

**Issue by 23jodys** [23jodys/fealden#12]
```Output from webfealden:
###### 

convert: unable to open image `/var/fealden/solutions/0fa36579849c4e93a14bb3c3e2fb751b/TCTAATTATAGATCCATAATTGG_1.png': No such file or directory @ blob.c/OpenBlob/2480.
convert: unable to open file`/var/fealden/solutions/0fa36579849c4e93a14bb3c3e2fb751b/TCTAATTATAGATCCATAATTGG_1.png' @ png.c/ReadPNGImage/2921.
convert: missing an image filename `/var/fealden/solutions/0fa36579849c4e93a14bb3c3e2fb751b/TCTAATTATAGATCCATAATTGG_1_t.png' @ convert.c/ConvertImageCommand/2838.
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib/python2.6/multiprocessing/process.py", line 88, in run
    self._target(_self._args, *_self._kwargs)
  File "/media/cargo/fealden/fealden/searchserver.py", line 147, in solutionworker
    cmd_dictionary[output_request.command](output_request)
  File "/media/cargo/fealden/fealden/searchserver.py", line 120, in _output_queue_WEBOUTPUT
    output_request.output_dir)
  File "/media/cargo/fealden/fealden/weboutput.py", line 101, in solution_output
    subprocess.check_call(' '.join(convert_command), shell=True)
  File "/usr/lib/python2.6/subprocess.py", line 498, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '/usr/bin/convert -scale 128x128 -border 10 -bordercolor  green /var/fealden/solutions/0fa36579849c4e93a14bb3c3e2fb751b/TCTAATTATAGATCCATAATTGG_1.png /var/fealden/solutions/0fa36579849c4e93a14bb3c3e2fb751b/TCTAATTATAGATCCATAATTGG_1_t.png' returned non-zero exit status 1
###### ########################################```

The program successfully created the /var/fealden/solutions/HugeString directory, but it is empty, so I suspect the imagemagick call above (which is for generating thumbnails) is failing because unafold is not generating the larger images in the first place.  Hmm...

**Comment by 23jodys** [comment]
Specifically, fealdend should check existence and permissions for all directories it needs to read and write from.

**Comment by Paradoxdruid** [comment]
Discovered the solution to this; it's part of issue #8.  mfold_util package needs to be installed to generate graphs.
