### ISSUE TITLE
Fealdend finds solution but does not report it to webfealden.py

### ISSUE THREAD

**Issue by Paradoxdruid** [23jodys/fealden#15]
Ran "ATTA" and page refreshed endlessly.  Stopped and checked /var/fealden/fealdend.log:
###### 

```
2013-06-12 13:16:32,683:INFO:fealden.searchserver:searchworker(1719): got BACKTRACKING for ATTA
2013-06-12 13:16:32,684:INFO:fealden.searchserver:searchworker(1719): ATTA dispatched to _request_queue_BACKTRACKING  
2013-06-12 13:16:32,684:INFO:fealden.searchserver:sensor.Recognition is ATTA
2013-06-12 13:16:32,701:INFO:fealden.backtracking:sensorsearch(...): QUEUE -- DEPTH(1) is now maxdepth
2013-06-12 13:16:32,702:INFO:fealden.backtracking:sensorsearch(...): QUEUE -- DEPTH(2) is now maxdepth
2013-06-12 13:16:32,702:INFO:fealden.backtracking:sensorsearch(...): QUEUE -- DEPTH(3) is now maxdepth
2013-06-12 13:16:32,703:INFO:fealden.backtracking:sensorsearch(...): QUEUE -- DEPTH(4) is now maxdepth
2013-06-12 13:16:32,703:INFO:fealden.backtracking:sensorsearch(...): QUEUE -- DEPTH(5) is now maxdepth
2013-06-12 13:16:32,776:DEBUG:fealden.unafold:unafold.validate_sensor(TCCATTAGGATCCCTAATGGG): GOOD -- 2 folds within 2 to 8
2013-06-12 13:16:32,777:DEBUG:fealden.unafold:unafold.validate_sensor(TCCATTAGGATCCCTAATGGG): BAD -- highest fold free energy,-7.719000 exceeds max of -6.400000
2013-06-12 13:16:32,777:DEBUG:fealden.unafold:unafold.validate_sensor(TCCATTAGGATCCCTAATGGG): BAD -- binding ratio (1.000000 vs 0.000000) out of range 0.900000 < 0.00$
2013-06-12 13:16:32,777:DEBUG:fealden.unafold:unafold.validate_sensor(TCCATTAGGATCCCTAATGGG): GOOD -- unknown percentage, 0.000000, below max 0.100000
2013-06-12 13:16:32,778:DEBUG:fealden.unafold:unafold.validate_sensor(TCCATTAGGATCCCTAATGGG): found invalid solution
2013-06-12 13:16:32,778:INFO:fealden.backtracking:sensorsearch(...): QUEUE -- INVALID SOLUTION TCCATTAGGATCCCTAATGGG  
2013-06-12 13:16:32,784:INFO:fealden.backtracking:sensorsearch(...): QUEUE -- DEPTH(6) is now maxdepth
2013-06-12 13:16:32,908:DEBUG:fealden.unafold:unafold.validate_sensor(TCCCATTAGGGATCCATAATTGG): GOOD -- 3 folds within 2 to 8
2013-06-12 13:16:32,909:DEBUG:fealden.unafold:unafold.validate_sensor(TCCCATTAGGGATCCATAATTGG): GOOD -- highest fold free energy, -4.587000 does not exceed max of -6.$
2013-06-12 13:16:32,909:DEBUG:fealden.unafold:unafold.validate_sensor(TCCCATTAGGGATCCATAATTGG): BAD -- binding ratio (0.000000 vs 1.000000) out of range 0.900000 < 0.$
2013-06-12 13:16:32,909:DEBUG:fealden.unafold:unafold.validate_sensor(TCCCATTAGGGATCCATAATTGG): GOOD -- unknown percentage, 0.000000, below max 0.100000
2013-06-12 13:16:32,910:DEBUG:fealden.unafold:unafold.validate_sensor(TCCCATTAGGGATCCATAATTGG): found invalid solution
2013-06-12 13:16:32,910:INFO:fealden.backtracking:sensorsearch(...): QUEUE -- INVALID SOLUTION TCCCATTAGGGATCCATAATTGG
2013-06-12 13:16:32,984:DEBUG:fealden.unafold:unafold.validate_sensor(TCCAATTATGGATCCATAATTGG): BAD -- 1 folds not within 2 to 8
```

.... skip many invalid solutions ......

```
2013-06-12 13:16:34,722:DEBUG:fealden.unafold:unafold.validate_sensor(TCTAATTATAGATCCATAATTGG): GOOD -- 4 folds within 2 to 8
2013-06-12 13:16:34,722:DEBUG:fealden.unafold:unafold.validate_sensor(TCTAATTATAGATCCATAATTGG): GOOD -- highest fold free energy, -2.987000 does not exceed max of -6.$
2013-06-12 13:16:34,722:DEBUG:fealden.unafold:unafold.validate_sensor(TCTAATTATAGATCCATAATTGG): GOOD -- binding ratio(0.521553 vs 0.478447) in range 0.900000 < 1.0900$
2013-06-12 13:16:34,723:DEBUG:fealden.unafold:unafold.validate_sensor(TCTAATTATAGATCCATAATTGG): GOOD -- unknown percentage, 0.000000, below max 0.100000
2013-06-12 13:16:34,723:INFO:fealden.unafold:unafold.validate_sensor(TCTAATTATAGATCCATAATTGG): found valid solution
2013-06-12 13:16:34,723:INFO:fealden.backtracking:sensorsearch(...): QUEUE -- VALID SOLUTION SOLUTION
```

So a valid solution was found, but didn't get communicated back.  I suspect this is still a directory permission issue.  I am running fealdend and webfealden as sudo, passing PYTHONPATH to sudo for fealden to work.

**Comment by Paradoxdruid** [comment]
After commenting out the affinity plot legend (to deal with Issue #17 ), fealden found a solution but couldn't report it.

Fealdend.log shows:

```
2013-06-14 11:10:17,388:DEBUG:fealden.unafold:unafold.validate_sensor(TCTCATATAGAGATCCTTATATAGG): GOOD -- unknown percentage, 0.000000, below max 0.100000
2013-06-14 11:10:17,389:DEBUG:fealden.unafold:unafold.validate_sensor(TCTCATATAGAGATCCTTATATAGG): found invalid solution
2013-06-14 11:10:17,389:INFO:fealden.backtracking:sensorsearch(...): QUEUE -- INVALID SOLUTION TCTCATATAGAGATCCTTATATAGG
2013-06-14 11:10:17,418:DEBUG:fealden.unafold:unafold.validate_sensor(TCTAATATATAGATCCTCTATATGAGG): GOOD -- 5 folds within 2 to 8
2013-06-14 11:10:17,418:DEBUG:fealden.unafold:unafold.validate_sensor(TCTAATATATAGATCCTCTATATGAGG): GOOD -- highest fold free energy, -4.776000 does not exceed max of -7.000000
2013-06-14 11:10:17,419:DEBUG:fealden.unafold:unafold.validate_sensor(TCTAATATATAGATCCTCTATATGAGG): GOOD -- binding ratio(0.507543 vs 0.492457) in range 0.900000 < 1.030636 < 1.100000
2013-06-14 11:10:17,419:DEBUG:fealden.unafold:unafold.validate_sensor(TCTAATATATAGATCCTCTATATGAGG): GOOD -- unknown percentage, 0.000000, below max 0.100000
2013-06-14 11:10:17,419:INFO:fealden.unafold:unafold.validate_sensor(TCTAATATATAGATCCTCTATATGAGG): found valid solution
2013-06-14 11:10:17,420:INFO:fealden.backtracking:sensorsearch(...): QUEUE -- VALID SOLUTION SOLUTION
2013-06-14 11:10:17,428:INFO:fealden.searchserver:solutionworker(14978): CMD: WEBOUTPUT STAT: found on TCTAATATATAGATCCTCTATATGAGG
```

While webfealden.py crashed with:

```
127.0.0.1:34128 - - [03/Jul/2013 14:19:10] "HTTP/1.1 GET /solution/38e83c15824b417baa5902b456cb70eb/" - 200 OK
127.0.0.1:34128 - - [03/Jul/2013 14:19:12] "HTTP/1.1 GET /favicon.ico" - 404 Not Found
Traceback (most recent call last):
  File "/media/cargo/fealden/web/web/application.py", line 239, in process
  File "/media/cargo/fealden/web/web/application.py", line 230, in handle
  File "/media/cargo/fealden/web/web/application.py", line 420, in _delegate
  File "/media/cargo/fealden/web/web/application.py", line 396, in handle_class
  File "/media/cargo/fealden/web/webfealden.py", line 64, in GET
    return render.solution(sensor, scores, folds, unique_id)
  File "/media/cargo/fealden/web/web/template.py", line 1020, in template
  File "/media/cargo/fealden/web/web/template.py", line 881, in __call__
  File "/media/cargo/fealden/web/web/template.py", line 808, in __call__
  File "templates/solution.html", line 20, in __template__
    </ul>
ValueError: zero length field name in format
```

and the output page in the browser crashed with a zero length field error, somewhere in this line:

```
<li>Binding -- Signal ON: $"{:.0%}".format(scores["binding_on"]["percent"])</li> 
```

**Comment by 23jodys** [comment]
This is actually an issue with format strings in python. Version 2.6 requires indicies in the format strings, 2.7 (like the post 3.1 versions) does not. I've updated all four of the format strings so that they will work with 2.6 and tested it against a 2.6 interpreter.
