### ISSUE TITLE
Weboutput affinity plot numpy error

### ISSUE THREAD

**Issue by Paradoxdruid** [23jodys/fealden#17]
Looks like an error processing the numbers for affinity plots.  Relevant bit:  'numpy.float64 ' object has no attribute 'startswith'

```
python webfealden.py
http://0.0.0.0:8080/
127.0.0.1:48904 - - [14/Jun/2013 11:10:01] "HTTP/1.1 GET /" - 200 OK
127.0.0.1:48904 - - [14/Jun/2013 11:10:02] "HTTP/1.1 GET /favicon.ico" - 404 Not Found
127.0.0.1:48904 - - [14/Jun/2013 11:10:04] "HTTP/1.1 GET /favicon.ico" - 404 Not Found
127.0.0.1:48904 - - [14/Jun/2013 11:10:10] "HTTP/1.1 POST /" - 303 See Other
127.0.0.1:48904 - - [14/Jun/2013 11:10:10] "HTTP/1.1 GET /solution/4ce251b84e964c43a94b1e4e25d3fc3a/" - 200 OK
127.0.0.1:48904 - - [14/Jun/2013 11:10:11] "HTTP/1.1 GET /favicon.ico" - 404 Not Found
127.0.0.1:48904 - - [14/Jun/2013 11:10:16] "HTTP/1.1 GET /solution/4ce251b84e964c43a94b1e4e25d3fc3a/" - 200 OK
127.0.0.1:48904 - - [14/Jun/2013 11:10:16] "HTTP/1.1 GET /favicon.ico" - 404 Not Found
127.0.0.1:48904 - - [14/Jun/2013 11:10:21] "HTTP/1.1 GET /solution/4ce251b84e964c43a94b1e4e25d3fc3a/" - 200 OK
127.0.0.1:48904 - - [14/Jun/2013 11:10:22] "HTTP/1.1 GET /favicon.ico" - 404 Not Found
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/media/cargo/fealden/fealden/searchserver.py", line 149, in solutionworker
    cmd_dictionary[output_request.command](output_request)
  File "/media/cargo/fealden/fealden/searchserver.py", line 120, in _output_queue_WEBOUTPUT
    output_request.output_dir)
  File "/media/cargo/fealden/fealden/weboutput.py", line 124, in solution_output
    plot_gain(Ks, sensor, output_dir)
  File "/media/cargo/fealden/fealden/weboutput.py", line 161, in plot_gain
    ncol=2, shadow=True, title="Affinity with K_s = %f" %(Ks))
  File "/usr/lib/pymodules/python2.6/matplotlib/axes.py", line 4012, in legend
    handles, labels = self.get_legend_handles_labels()
  File "/usr/lib/pymodules/python2.6/matplotlib/axes.py", line 3859, in get_legend_handles_labels
    label != '' and not label.startswith('_')):
AttributeError: 'numpy.float64' object has no attribute 'startswith'
```

**Comment by Paradoxdruid** [comment]
I suspect that this issue and Issue #18 both stem from the same root cause; some data not being found or reported.

**Comment by Paradoxdruid** [comment]
Latest release still is returning errors on affinity plotting:

```
127.0.0.1:34088 - - [03/Jul/2013 13:09:28] "HTTP/1.1 GET /favicon.ico" - 404 Not Found
127.0.0.1:34088 - - [03/Jul/2013 13:09:33] "HTTP/1.1 GET /solution/5584f620b44f4e53bc4d052f96e6770e/" - 200 OK
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/media/cargo/fealden/fealden/searchserver.py", line 158, in solutionworker
    cmd_dictionary[output_request.command](output_request)
  File "/media/cargo/fealden/fealden/searchserver.py", line 129, in _output_queue_WEBOUTPUT
    output_request.output_dir)
  File "/media/cargo/fealden/fealden/weboutput.py", line 124, in solution_output
    plot_gain(Ks, sensor, output_dir)
  File "/media/cargo/fealden/fealden/weboutput.py", line 161, in plot_gain
    ncol=2, shadow=True, title="Affinity with K_s = %f" %(Ks))
  File "/usr/lib/pymodules/python2.6/matplotlib/axes.py", line 4012, in legend
    handles, labels = self.get_legend_handles_labels()
  File "/usr/lib/pymodules/python2.6/matplotlib/axes.py", line 3859, in get_legend_handles_labels
    label != '' and not label.startswith('_')):
AttributeError: 'numpy.float64' object has no attribute 'startswith'
2013-07-03 13:09:44,466:ERROR:signalhandler:12163: One of our searchworker/outputworker had a fatal error.
2013-07-03 13:09:44,468:ERROR:signalhandler:Exiting....
2013-07-03 13:09:44,469:ERROR:signalhandler:12163: One of our searchworker/outputworker had a fatal error.
2013-07-03 13:09:44,469:ERROR:signalhandler:Exiting....
Exiting...
```

**Comment by 23jodys** [comment]
The matplotlib that comes with Python 2.6 (in Debian) has a bug such that labels for plots must be strings (hence it expecting a startswith() method). In one of the lines before where this errors, we set the labels for each plot to be a float (affinity). I've created a string formatting to cast the float as a string and this issue is resolved. This does not happen in the latest matplotlib.
