### ISSUE TITLE
Solution.html Template has zero length fields

### ISSUE THREAD

**Issue by Paradoxdruid** [23jodys/fealden#18]
Latest error:

```
 python webfealden.py
http://0.0.0.0:8080/
127.0.0.1:50390 - - [27/Jun/2013 07:03:51] "HTTP/1.1 GET /" - 200 OK
127.0.0.1:50390 - - [27/Jun/2013 07:03:52] "HTTP/1.1 GET /favicon.ico" - 404 Not Found
127.0.0.1:50390 - - [27/Jun/2013 07:03:58] "HTTP/1.1 POST /" - 303 See Other
127.0.0.1:50390 - - [27/Jun/2013 07:03:58] "HTTP/1.1 GET /solution/325927d540a94c2f9204ccdd9798c44a/" - 200 OK
127.0.0.1:50390 - - [27/Jun/2013 07:03:59] "HTTP/1.1 GET /favicon.ico" - 404 Not Found
127.0.0.1:50390 - - [27/Jun/2013 07:04:04] "HTTP/1.1 GET /solution/325927d540a94c2f9204ccdd9798c44a/" - 200 OK
127.0.0.1:50390 - - [27/Jun/2013 07:04:04] "HTTP/1.1 GET /favicon.ico" - 404 Not Found
Traceback (most recent call last):
  File "/media/cargo/fealden/web/web/application.py", line 239, in process
    return self.handle()
  File "/media/cargo/fealden/web/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/media/cargo/fealden/web/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/media/cargo/fealden/web/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "/media/cargo/fealden/web/webfealden.py", line 64, in GET
    return render.solution(sensor, scores, folds, unique_id)
  File "/media/cargo/fealden/web/web/template.py", line 1020, in template
    return self._base(t(*a, **kw))
  File "/media/cargo/fealden/web/web/template.py", line 881, in __call__
    return BaseTemplate.__call__(self, *a, **kw)
  File "/media/cargo/fealden/web/web/template.py", line 808, in __call__
    return self.t(*a, **kw)
  File "templates/solution.html", line 20, in __template__
    </ul>
ValueError: zero length field name in format
```

I think it's because some data (sensor, scores, etc) is not getting reported correctly.

It might be pertinent:  I used the new fealden.ini to redirect all the /var directory entries to a local user-accessible directory (and had to touch fealdend.log to make it work).

**Comment by 23jodys** [comment]
Same as issue #17, related to using Python 2.6. This has been resolved.
