### ISSUE TITLE
Search timeouts should generate a failure page

### ISSUE THREAD

**Issue by 23jodys** [23jodys/fealden#23]

**Comment by Paradoxdruid** [comment]
Just chiming in; yes, I think this is the missing feature of greatest import at this point.  Independent server install works fine until this error happens:

```
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/media/cargo/fealden/fealden/searchserver.py", line 158, in solutionworker
    cmd_dictionary[output_request.command](output_request)
  File "/media/cargo/fealden/fealden/searchserver.py", line 134, in _output_queue_WEBOUTPUT
    output_request.output_dir)
TypeError: failed_output() takes exactly 3 arguments (2 given)
Exiting...
```

So, failed_output is not only not generating a page, but it's killing fealdend, so the server stops working on any sensor until the processes are manually restarted.

**Comment by 23jodys** [comment]
Got it. Should be fixed now in latest commit. Also, fealden.ini now has a timeout parameter to customize how long before fealdend will timeout the search.
